In [3]:
import numpy as np

Ufanc


In [7]:
v = np.array([1,2,3,4,5])
v


array([1, 2, 3, 4, 5])

In [8]:
np.subtract(v , 1)

array([0, 1, 2, 3, 4])

In [10]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [11]:
np.multiply(v, 2)

array([ 2,  4,  6,  8, 10])

In [12]:
np.divide(v, 2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [14]:
v**2

array([ 1,  4,  9, 16, 25])

In [15]:
np.power(v , 3)

array([  1,   8,  27,  64, 125])

In [16]:
v % 2

array([1, 0, 1, 0, 1])

In [17]:
np.mod(v,2)

array([1, 0, 1, 0, 1])

In [18]:
np.sin(60)

np.float64(-0.3048106211022167)

In [19]:
np.sin(90)

np.float64(0.8939966636005579)

In [20]:
np.cos(90)

np.float64(-0.4480736161291701)

In [21]:
v = np.array([1,2,3])
np.log(v)

array([0.        , 0.69314718, 1.09861229])