In [5]:
import numpy as np


In [4]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
a = np.array([1,2,3])
type(a)


numpy.ndarray

In [8]:
np.array([1.5 ,12,13,5])

array([ 1.5, 12. , 13. ,  5. ])

In [12]:
np.array([1,8,2,3], dtype="int")


array([1, 8, 2, 3])

In [16]:
np.ones((2,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
np.full((5,3), 12)

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [23]:
np.arange(1,40,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [24]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [25]:
np.random.normal(10,4 , (3,4))

array([[ 8.60316948, 17.40967966,  4.85703935, -0.50932914],
       [ 6.27317043, 10.07005185, 12.67091007, 14.09370847],
       [ 9.80074284, 10.05394115, 11.27467938,  6.81446688]])