In [2]:
import numpy as np

In [4]:

pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
np.random.randint(10 , size = 5)

array([2, 2, 0, 3, 8], dtype=int32)

In [10]:
a = np.random.randint(10 , size = 5)
type(a)

numpy.ndarray

In [12]:
a.shape

(5,)

In [13]:
a.dtype

dtype('int32')

In [14]:
b = np.random.randint(10 , size= (3,5))

In [15]:
b

array([[1, 1, 7, 2, 2],
       [4, 1, 1, 8, 4],
       [1, 7, 8, 5, 2]], dtype=int32)

In [16]:
b.ndim

2

In [17]:
b.shape

(3, 5)

In [18]:
b.size

15

In [19]:
b.dtype

dtype('int32')

**reshape

In [22]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

*connection


In [32]:
x = np.array([1,2,3])
y = np.array ([4,5,6])

In [34]:
z = np.concatenate([x , y])


In [35]:
z

array([1, 2, 3, 4, 5, 6])

In [36]:
e = np.array([7,8,9])

np.concatenate([z,e])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
 k = np.array([[1,2,3],
          [4,5,6]])

In [48]:
np.concatenate([k,k])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
np.concatenate([k,k], axis= 1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

splitting


In [54]:
h = np.array([1,2,3,43,43,3,2,1])

In [66]:
np.split(h, [3,5])

[array([1, 2, 3]), array([43, 43]), array([3, 2, 1])]

In [67]:
a,b,c = np.split(h, [3,5])

In [68]:
a


array([1, 2, 3])

In [69]:
b

array([43, 43])

In [70]:
c

array([3, 2, 1])

In [77]:
m = np.arange(16).reshape(4,4)
m


(4, 4)

Sorting


In [79]:
v = np.array([4,3,6,1,7,5,3])
v.sort()
v

array([1, 3, 3, 4, 5, 6, 7])

In [87]:
l = np.random.normal(20,5, (3,3))
l.sort()
l

array([[16.68420152, 17.30628233, 17.35003594],
       [10.44472941, 17.02008923, 20.25582614],
       [16.49060592, 22.76136068, 30.9632103 ]])

axis den istifade ederek hem sutunlari hem siralari, sort etmek olur

In [7]:
c = np.random.randint(10 , size= (4,4) )

In [8]:
c[::]

array([[2, 0, 4, 0],
       [3, 5, 4, 4],
       [7, 5, 9, 0],
       [4, 3, 7, 1]], dtype=int32)

In [9]:
c[::,0:2]

array([[2, 0],
       [3, 5],
       [7, 5],
       [4, 3]], dtype=int32)

In [10]:
c[:2,:2]

array([[2, 0],
       [3, 5]], dtype=int32)

In [11]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])